require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompletedCheckpointsController do

  # This should return the minimal set of attributes required to create a valid
  # CompletedCheckpoint. As you add validations to CompletedCheckpoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "checkpoint_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompletedCheckpointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all completed_checkpoints as @completed_checkpoints" do
      completed_checkpoint = CompletedCheckpoint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:completed_checkpoints).should eq([completed_checkpoint])
    end
  end

  describe "GET show" do
    it "assigns the requested completed_checkpoint as @completed_checkpoint" do
      completed_checkpoint = CompletedCheckpoint.create! valid_attributes
      get :show, {:id => completed_checkpoint.to_param}, valid_session
      assigns(:completed_checkpoint).should eq(completed_checkpoint)
    end
  end

  describe "GET new" do
    it "assigns a new completed_checkpoint as @completed_checkpoint" do
      get :new, {}, valid_session
      assigns(:completed_checkpoint).should be_a_new(CompletedCheckpoint)
    end
  end

  describe "GET edit" do
    it "assigns the requested completed_checkpoint as @completed_checkpoint" do
      completed_checkpoint = CompletedCheckpoint.create! valid_attributes
      get :edit, {:id => completed_checkpoint.to_param}, valid_session
      assigns(:completed_checkpoint).should eq(completed_checkpoint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompletedCheckpoint" do
        expect {
          post :create, {:completed_checkpoint => valid_attributes}, valid_session
        }.to change(CompletedCheckpoint, :count).by(1)
      end

      it "assigns a newly created completed_checkpoint as @completed_checkpoint" do
        post :create, {:completed_checkpoint => valid_attributes}, valid_session
        assigns(:completed_checkpoint).should be_a(CompletedCheckpoint)
        assigns(:completed_checkpoint).should be_persisted
      end

      it "redirects to the created completed_checkpoint" do
        post :create, {:completed_checkpoint => valid_attributes}, valid_session
        response.should redirect_to(CompletedCheckpoint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved completed_checkpoint as @completed_checkpoint" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedCheckpoint.any_instance.stub(:save).and_return(false)
        post :create, {:completed_checkpoint => { "checkpoint_id" => "invalid value" }}, valid_session
        assigns(:completed_checkpoint).should be_a_new(CompletedCheckpoint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedCheckpoint.any_instance.stub(:save).and_return(false)
        post :create, {:completed_checkpoint => { "checkpoint_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested completed_checkpoint" do
        completed_checkpoint = CompletedCheckpoint.create! valid_attributes
        # Assuming there are no other completed_checkpoints in the database, this
        # specifies that the CompletedCheckpoint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompletedCheckpoint.any_instance.should_receive(:update).with({ "checkpoint_id" => "1" })
        put :update, {:id => completed_checkpoint.to_param, :completed_checkpoint => { "checkpoint_id" => "1" }}, valid_session
      end

      it "assigns the requested completed_checkpoint as @completed_checkpoint" do
        completed_checkpoint = CompletedCheckpoint.create! valid_attributes
        put :update, {:id => completed_checkpoint.to_param, :completed_checkpoint => valid_attributes}, valid_session
        assigns(:completed_checkpoint).should eq(completed_checkpoint)
      end

      it "redirects to the completed_checkpoint" do
        completed_checkpoint = CompletedCheckpoint.create! valid_attributes
        put :update, {:id => completed_checkpoint.to_param, :completed_checkpoint => valid_attributes}, valid_session
        response.should redirect_to(completed_checkpoint)
      end
    end

    describe "with invalid params" do
      it "assigns the completed_checkpoint as @completed_checkpoint" do
        completed_checkpoint = CompletedCheckpoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedCheckpoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => completed_checkpoint.to_param, :completed_checkpoint => { "checkpoint_id" => "invalid value" }}, valid_session
        assigns(:completed_checkpoint).should eq(completed_checkpoint)
      end

      it "re-renders the 'edit' template" do
        completed_checkpoint = CompletedCheckpoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedCheckpoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => completed_checkpoint.to_param, :completed_checkpoint => { "checkpoint_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested completed_checkpoint" do
      completed_checkpoint = CompletedCheckpoint.create! valid_attributes
      expect {
        delete :destroy, {:id => completed_checkpoint.to_param}, valid_session
      }.to change(CompletedCheckpoint, :count).by(-1)
    end

    it "redirects to the completed_checkpoints list" do
      completed_checkpoint = CompletedCheckpoint.create! valid_attributes
      delete :destroy, {:id => completed_checkpoint.to_param}, valid_session
      response.should redirect_to(completed_checkpoints_url)
    end
  end

end
