require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstructionalCoachesController do

  # This should return the minimal set of attributes required to create a valid
  # InstructionalCoach. As you add validations to InstructionalCoach, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstructionalCoachesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all instructional_coaches as @instructional_coaches" do
      instructional_coach = InstructionalCoach.create! valid_attributes
      get :index, {}, valid_session
      assigns(:instructional_coaches).should eq([instructional_coach])
    end
  end

  describe "GET show" do
    it "assigns the requested instructional_coach as @instructional_coach" do
      instructional_coach = InstructionalCoach.create! valid_attributes
      get :show, {:id => instructional_coach.to_param}, valid_session
      assigns(:instructional_coach).should eq(instructional_coach)
    end
  end

  describe "GET new" do
    it "assigns a new instructional_coach as @instructional_coach" do
      get :new, {}, valid_session
      assigns(:instructional_coach).should be_a_new(InstructionalCoach)
    end
  end

  describe "GET edit" do
    it "assigns the requested instructional_coach as @instructional_coach" do
      instructional_coach = InstructionalCoach.create! valid_attributes
      get :edit, {:id => instructional_coach.to_param}, valid_session
      assigns(:instructional_coach).should eq(instructional_coach)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstructionalCoach" do
        expect {
          post :create, {:instructional_coach => valid_attributes}, valid_session
        }.to change(InstructionalCoach, :count).by(1)
      end

      it "assigns a newly created instructional_coach as @instructional_coach" do
        post :create, {:instructional_coach => valid_attributes}, valid_session
        assigns(:instructional_coach).should be_a(InstructionalCoach)
        assigns(:instructional_coach).should be_persisted
      end

      it "redirects to the created instructional_coach" do
        post :create, {:instructional_coach => valid_attributes}, valid_session
        response.should redirect_to(InstructionalCoach.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instructional_coach as @instructional_coach" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionalCoach.any_instance.stub(:save).and_return(false)
        post :create, {:instructional_coach => {  }}, valid_session
        assigns(:instructional_coach).should be_a_new(InstructionalCoach)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionalCoach.any_instance.stub(:save).and_return(false)
        post :create, {:instructional_coach => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instructional_coach" do
        instructional_coach = InstructionalCoach.create! valid_attributes
        # Assuming there are no other instructional_coaches in the database, this
        # specifies that the InstructionalCoach created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstructionalCoach.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => instructional_coach.to_param, :instructional_coach => { "these" => "params" }}, valid_session
      end

      it "assigns the requested instructional_coach as @instructional_coach" do
        instructional_coach = InstructionalCoach.create! valid_attributes
        put :update, {:id => instructional_coach.to_param, :instructional_coach => valid_attributes}, valid_session
        assigns(:instructional_coach).should eq(instructional_coach)
      end

      it "redirects to the instructional_coach" do
        instructional_coach = InstructionalCoach.create! valid_attributes
        put :update, {:id => instructional_coach.to_param, :instructional_coach => valid_attributes}, valid_session
        response.should redirect_to(instructional_coach)
      end
    end

    describe "with invalid params" do
      it "assigns the instructional_coach as @instructional_coach" do
        instructional_coach = InstructionalCoach.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionalCoach.any_instance.stub(:save).and_return(false)
        put :update, {:id => instructional_coach.to_param, :instructional_coach => {  }}, valid_session
        assigns(:instructional_coach).should eq(instructional_coach)
      end

      it "re-renders the 'edit' template" do
        instructional_coach = InstructionalCoach.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionalCoach.any_instance.stub(:save).and_return(false)
        put :update, {:id => instructional_coach.to_param, :instructional_coach => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instructional_coach" do
      instructional_coach = InstructionalCoach.create! valid_attributes
      expect {
        delete :destroy, {:id => instructional_coach.to_param}, valid_session
      }.to change(InstructionalCoach, :count).by(-1)
    end

    it "redirects to the instructional_coaches list" do
      instructional_coach = InstructionalCoach.create! valid_attributes
      delete :destroy, {:id => instructional_coach.to_param}, valid_session
      response.should redirect_to(instructional_coaches_url)
    end
  end

end
