require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParentQuestionsController do

  # This should return the minimal set of attributes required to create a valid
  # ParentQuestion. As you add validations to ParentQuestion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParentQuestionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all parent_questions as @parent_questions" do
      parent_question = ParentQuestion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:parent_questions).should eq([parent_question])
    end
  end

  describe "GET show" do
    it "assigns the requested parent_question as @parent_question" do
      parent_question = ParentQuestion.create! valid_attributes
      get :show, {:id => parent_question.to_param}, valid_session
      assigns(:parent_question).should eq(parent_question)
    end
  end

  describe "GET new" do
    it "assigns a new parent_question as @parent_question" do
      get :new, {}, valid_session
      assigns(:parent_question).should be_a_new(ParentQuestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested parent_question as @parent_question" do
      parent_question = ParentQuestion.create! valid_attributes
      get :edit, {:id => parent_question.to_param}, valid_session
      assigns(:parent_question).should eq(parent_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ParentQuestion" do
        expect {
          post :create, {:parent_question => valid_attributes}, valid_session
        }.to change(ParentQuestion, :count).by(1)
      end

      it "assigns a newly created parent_question as @parent_question" do
        post :create, {:parent_question => valid_attributes}, valid_session
        assigns(:parent_question).should be_a(ParentQuestion)
        assigns(:parent_question).should be_persisted
      end

      it "redirects to the created parent_question" do
        post :create, {:parent_question => valid_attributes}, valid_session
        response.should redirect_to(ParentQuestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved parent_question as @parent_question" do
        # Trigger the behavior that occurs when invalid params are submitted
        ParentQuestion.any_instance.stub(:save).and_return(false)
        post :create, {:parent_question => {  }}, valid_session
        assigns(:parent_question).should be_a_new(ParentQuestion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ParentQuestion.any_instance.stub(:save).and_return(false)
        post :create, {:parent_question => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested parent_question" do
        parent_question = ParentQuestion.create! valid_attributes
        # Assuming there are no other parent_questions in the database, this
        # specifies that the ParentQuestion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ParentQuestion.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => parent_question.to_param, :parent_question => { "these" => "params" }}, valid_session
      end

      it "assigns the requested parent_question as @parent_question" do
        parent_question = ParentQuestion.create! valid_attributes
        put :update, {:id => parent_question.to_param, :parent_question => valid_attributes}, valid_session
        assigns(:parent_question).should eq(parent_question)
      end

      it "redirects to the parent_question" do
        parent_question = ParentQuestion.create! valid_attributes
        put :update, {:id => parent_question.to_param, :parent_question => valid_attributes}, valid_session
        response.should redirect_to(parent_question)
      end
    end

    describe "with invalid params" do
      it "assigns the parent_question as @parent_question" do
        parent_question = ParentQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ParentQuestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => parent_question.to_param, :parent_question => {  }}, valid_session
        assigns(:parent_question).should eq(parent_question)
      end

      it "re-renders the 'edit' template" do
        parent_question = ParentQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ParentQuestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => parent_question.to_param, :parent_question => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested parent_question" do
      parent_question = ParentQuestion.create! valid_attributes
      expect {
        delete :destroy, {:id => parent_question.to_param}, valid_session
      }.to change(ParentQuestion, :count).by(-1)
    end

    it "redirects to the parent_questions list" do
      parent_question = ParentQuestion.create! valid_attributes
      delete :destroy, {:id => parent_question.to_param}, valid_session
      response.should redirect_to(parent_questions_url)
    end
  end

end
