require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnswersSetsController do

  # This should return the minimal set of attributes required to create a valid
  # AnswersSet. As you add validations to AnswersSet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnswersSetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all answers_sets as @answers_sets" do
      answers_set = AnswersSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:answers_sets).should eq([answers_set])
    end
  end

  describe "GET show" do
    it "assigns the requested answers_set as @answers_set" do
      answers_set = AnswersSet.create! valid_attributes
      get :show, {:id => answers_set.to_param}, valid_session
      assigns(:answers_set).should eq(answers_set)
    end
  end

  describe "GET new" do
    it "assigns a new answers_set as @answers_set" do
      get :new, {}, valid_session
      assigns(:answers_set).should be_a_new(AnswersSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested answers_set as @answers_set" do
      answers_set = AnswersSet.create! valid_attributes
      get :edit, {:id => answers_set.to_param}, valid_session
      assigns(:answers_set).should eq(answers_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnswersSet" do
        expect {
          post :create, {:answers_set => valid_attributes}, valid_session
        }.to change(AnswersSet, :count).by(1)
      end

      it "assigns a newly created answers_set as @answers_set" do
        post :create, {:answers_set => valid_attributes}, valid_session
        assigns(:answers_set).should be_a(AnswersSet)
        assigns(:answers_set).should be_persisted
      end

      it "redirects to the created answers_set" do
        post :create, {:answers_set => valid_attributes}, valid_session
        response.should redirect_to(AnswersSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved answers_set as @answers_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnswersSet.any_instance.stub(:save).and_return(false)
        post :create, {:answers_set => { "question_id" => "invalid value" }}, valid_session
        assigns(:answers_set).should be_a_new(AnswersSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnswersSet.any_instance.stub(:save).and_return(false)
        post :create, {:answers_set => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested answers_set" do
        answers_set = AnswersSet.create! valid_attributes
        # Assuming there are no other answers_sets in the database, this
        # specifies that the AnswersSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnswersSet.any_instance.should_receive(:update).with({ "question_id" => "1" })
        put :update, {:id => answers_set.to_param, :answers_set => { "question_id" => "1" }}, valid_session
      end

      it "assigns the requested answers_set as @answers_set" do
        answers_set = AnswersSet.create! valid_attributes
        put :update, {:id => answers_set.to_param, :answers_set => valid_attributes}, valid_session
        assigns(:answers_set).should eq(answers_set)
      end

      it "redirects to the answers_set" do
        answers_set = AnswersSet.create! valid_attributes
        put :update, {:id => answers_set.to_param, :answers_set => valid_attributes}, valid_session
        response.should redirect_to(answers_set)
      end
    end

    describe "with invalid params" do
      it "assigns the answers_set as @answers_set" do
        answers_set = AnswersSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnswersSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => answers_set.to_param, :answers_set => { "question_id" => "invalid value" }}, valid_session
        assigns(:answers_set).should eq(answers_set)
      end

      it "re-renders the 'edit' template" do
        answers_set = AnswersSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnswersSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => answers_set.to_param, :answers_set => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested answers_set" do
      answers_set = AnswersSet.create! valid_attributes
      expect {
        delete :destroy, {:id => answers_set.to_param}, valid_session
      }.to change(AnswersSet, :count).by(-1)
    end

    it "redirects to the answers_sets list" do
      answers_set = AnswersSet.create! valid_attributes
      delete :destroy, {:id => answers_set.to_param}, valid_session
      response.should redirect_to(answers_sets_url)
    end
  end

end
